const APPConfig = {
  API_URL: "https://atozbay.com/adminatoz/public/api",
};

const ApiEndPoints = {
  CustomerRegister: `${APPConfig.API_URL}/customer-register`,
  SellerRegister: `${APPConfig.API_URL}/seller-register`,
  SocialLogin: `${APPConfig.API_URL}/social-login`,
  Login: `${APPConfig.API_URL}/login`,
  ForgotPassword: `${APPConfig.API_URL}/forgot-password`,
  VerifyEmail: `${APPConfig.API_URL}/forgot-password-verify-otp`,
  ResetPassword: `${APPConfig.API_URL}/reset-password`,
  ChangePassword: `${APPConfig.API_URL}/change-password`,
  SendOTPEmail: `${APPConfig.API_URL}/send-otp-email`,
  VerifyEmailOTP: `${APPConfig.API_URL}/verify-email-otp`,
  CategoriesList: `${APPConfig.API_URL}/categories-list`,
  SubCategoriesList: `${APPConfig.API_URL}/subcategories-list/`,
  CountryList: `${APPConfig.API_URL}/countries-list`,
  StateList: `${APPConfig.API_URL}/states-list/`,
  CustomerProfile: `${APPConfig.API_URL}/customer-profile`,
  UpdateProfileImage: `${APPConfig.API_URL}/update-profile-image`,
  ContactInfo: `${APPConfig.API_URL}/update-contact-info`,
  GetContactInfo: `${APPConfig.API_URL}/get-contact-info`,
  UpdateCustomerProfile: `${APPConfig.API_URL}/update-customer-profile`,
  UpdateBusinessContactInfo: `${APPConfig.API_URL}/update-business-contact-info`,
  GetBusinessInfo: `${APPConfig.API_URL}/get-business-contact-info`,
  UpdatePaymentGateway: `${APPConfig.API_URL}/update-payment-gateway`,
  SellerProfile: `${APPConfig.API_URL}/seller-profile`,
  ColorList: `${APPConfig.API_URL}/colors-list`,
  AddAddress: `${APPConfig.API_URL}/address-add`,
  UpdateAddress: `${APPConfig.API_URL}/address-update/`,
  GetAddress: `${APPConfig.API_URL}/address/8`,
  ShipAddressList: `${APPConfig.API_URL}/addresses-list`,
  ProductAdd: `${APPConfig.API_URL}/product-add`,
  ProductUpdate: `${APPConfig.API_URL}/product-update/`,
  BrandList: `${APPConfig.API_URL}/brands-list`,
  AttributesList: `${APPConfig.API_URL}/attributes-list`,
  AttributesValueList: `${APPConfig.API_URL}/attributevalues-by-attribute/`,
  AttributesByCategory: `${APPConfig.API_URL}/attributes-by-category/`,
  ProductList: `${APPConfig.API_URL}/products-list`,
  ShopProductList: `${APPConfig.API_URL}/shop-products-list`,
  ProductSellerDetail: `${APPConfig.API_URL}/product/`,
  ProductSellDelete: `${APPConfig.API_URL}/product/`,
  ProductShopDetail: `${APPConfig.API_URL}/shop-product/`,
  // ProductShopDetail: `${APPConfig.API_URL}/shop-product-detail/`,
  AddToCart: `${APPConfig.API_URL}/add-to-cart`,
  CartProductsList: `${APPConfig.API_URL}/cart-products`,
  CartUpdate: `${APPConfig.API_URL}/update-cart`,
  CartProductCount: `${APPConfig.API_URL}/cart-product-count`,
  DeleteCartProduct: `${APPConfig.API_URL}/delete-cart-product`,
  AddToWishList: `${APPConfig.API_URL}/add-to-wishlist`,
  WishList: `${APPConfig.API_URL}/wishlist-products`,
  DeleteWishListProduct: `${APPConfig.API_URL}/delete-wishlist/`,
  WishListProductCount: `${APPConfig.API_URL}/wishlist-product-count`,
};

export default ApiEndPoints;
